//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM リレーションシップのメタデータ

[assembly: EdmRelationshipAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_CLIENT", "T_CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SekisanTeam.Models.T_CLIENT), "T_SEKISAN_DATA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SekisanTeam.Models.T_SEKISAN_DATA), true)]
[assembly: EdmRelationshipAttribute("sekisanModel", "FK_T_COMMENT_T_MEMBER", "T_MEMBER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SekisanTeam.Models.T_MEMBER), "T_COMMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SekisanTeam.Models.T_COMMENT), true)]
[assembly: EdmRelationshipAttribute("sekisanModel", "FK_T_COMMENT_T_SEKISAN_DATA", "T_SEKISAN_DATA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SekisanTeam.Models.T_SEKISAN_DATA), "T_COMMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SekisanTeam.Models.T_COMMENT), true)]
[assembly: EdmRelationshipAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_MASTER_DIFFICULT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SekisanTeam.Models.T_MASTER_DIFFICULT), "T_SEKISAN_DATA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SekisanTeam.Models.T_SEKISAN_DATA), true)]
[assembly: EdmRelationshipAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_MASTER_RATE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SekisanTeam.Models.T_MASTER_RATE), "T_SEKISAN_DATA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SekisanTeam.Models.T_SEKISAN_DATA), true)]
[assembly: EdmRelationshipAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MEMBER", "T_MEMBER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SekisanTeam.Models.T_MEMBER), "T_SEKISAN_DATA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SekisanTeam.Models.T_SEKISAN_DATA), true)]

#endregion

namespace SekisanTeam.Models
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class defaultEntity : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'defaultEntity' セクションにある接続文字列を使用して新しい defaultEntity オブジェクトを初期化します。
        /// </summary>
        public defaultEntity() : base("name=defaultEntity", "defaultEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい defaultEntity オブジェクトを初期化します。
        /// </summary>
        public defaultEntity(string connectionString) : base(connectionString, "defaultEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい defaultEntity オブジェクトを初期化します。
        /// </summary>
        public defaultEntity(EntityConnection connection) : base(connection, "defaultEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<T_CLIENT> T_CLIENT
        {
            get
            {
                if ((_T_CLIENT == null))
                {
                    _T_CLIENT = base.CreateObjectSet<T_CLIENT>("T_CLIENT");
                }
                return _T_CLIENT;
            }
        }
        private ObjectSet<T_CLIENT> _T_CLIENT;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<T_MASTER_DIFFICULT> T_MASTER_DIFFICULT
        {
            get
            {
                if ((_T_MASTER_DIFFICULT == null))
                {
                    _T_MASTER_DIFFICULT = base.CreateObjectSet<T_MASTER_DIFFICULT>("T_MASTER_DIFFICULT");
                }
                return _T_MASTER_DIFFICULT;
            }
        }
        private ObjectSet<T_MASTER_DIFFICULT> _T_MASTER_DIFFICULT;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<T_MASTER_RATE> T_MASTER_RATE
        {
            get
            {
                if ((_T_MASTER_RATE == null))
                {
                    _T_MASTER_RATE = base.CreateObjectSet<T_MASTER_RATE>("T_MASTER_RATE");
                }
                return _T_MASTER_RATE;
            }
        }
        private ObjectSet<T_MASTER_RATE> _T_MASTER_RATE;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<T_MEMBER> T_MEMBER
        {
            get
            {
                if ((_T_MEMBER == null))
                {
                    _T_MEMBER = base.CreateObjectSet<T_MEMBER>("T_MEMBER");
                }
                return _T_MEMBER;
            }
        }
        private ObjectSet<T_MEMBER> _T_MEMBER;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<T_COMMENT> T_COMMENT
        {
            get
            {
                if ((_T_COMMENT == null))
                {
                    _T_COMMENT = base.CreateObjectSet<T_COMMENT>("T_COMMENT");
                }
                return _T_COMMENT;
            }
        }
        private ObjectSet<T_COMMENT> _T_COMMENT;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<T_SEKISAN_DATA> T_SEKISAN_DATA
        {
            get
            {
                if ((_T_SEKISAN_DATA == null))
                {
                    _T_SEKISAN_DATA = base.CreateObjectSet<T_SEKISAN_DATA>("T_SEKISAN_DATA");
                }
                return _T_SEKISAN_DATA;
            }
        }
        private ObjectSet<T_SEKISAN_DATA> _T_SEKISAN_DATA;

        #endregion
        #region AddTo メソッド
    
        /// <summary>
        /// T_CLIENT EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToT_CLIENT(T_CLIENT t_CLIENT)
        {
            base.AddObject("T_CLIENT", t_CLIENT);
        }
    
        /// <summary>
        /// T_MASTER_DIFFICULT EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToT_MASTER_DIFFICULT(T_MASTER_DIFFICULT t_MASTER_DIFFICULT)
        {
            base.AddObject("T_MASTER_DIFFICULT", t_MASTER_DIFFICULT);
        }
    
        /// <summary>
        /// T_MASTER_RATE EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToT_MASTER_RATE(T_MASTER_RATE t_MASTER_RATE)
        {
            base.AddObject("T_MASTER_RATE", t_MASTER_RATE);
        }
    
        /// <summary>
        /// T_MEMBER EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToT_MEMBER(T_MEMBER t_MEMBER)
        {
            base.AddObject("T_MEMBER", t_MEMBER);
        }
    
        /// <summary>
        /// T_COMMENT EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToT_COMMENT(T_COMMENT t_COMMENT)
        {
            base.AddObject("T_COMMENT", t_COMMENT);
        }
    
        /// <summary>
        /// T_SEKISAN_DATA EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToT_SEKISAN_DATA(T_SEKISAN_DATA t_SEKISAN_DATA)
        {
            base.AddObject("T_SEKISAN_DATA", t_SEKISAN_DATA);
        }

        #endregion
    }
    

    #endregion
    
    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sekisanModel", Name="T_CLIENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_CLIENT : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい T_CLIENT オブジェクトを作成します。
        /// </summary>
        /// <param name="id">ID プロパティの初期値。</param>
        /// <param name="cODE">CODE プロパティの初期値。</param>
        /// <param name="nAME">NAME プロパティの初期値。</param>
        public static T_CLIENT CreateT_CLIENT(global::System.Int32 id, global::System.String cODE, global::System.String nAME)
        {
            T_CLIENT t_CLIENT = new T_CLIENT();
            t_CLIENT.ID = id;
            t_CLIENT.CODE = cODE;
            t_CLIENT.NAME = nAME;
            return t_CLIENT;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODE
        {
            get
            {
                return _CODE;
            }
            set
            {
                OnCODEChanging(value);
                ReportPropertyChanging("CODE");
                _CODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODE");
                OnCODEChanged();
            }
        }
        private global::System.String _CODE;
        partial void OnCODEChanging(global::System.String value);
        partial void OnCODEChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_CLIENT", "T_SEKISAN_DATA")]
        public EntityCollection<T_SEKISAN_DATA> T_SEKISAN_DATA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_CLIENT", "T_SEKISAN_DATA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_CLIENT", "T_SEKISAN_DATA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sekisanModel", Name="T_COMMENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_COMMENT : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい T_COMMENT オブジェクトを作成します。
        /// </summary>
        /// <param name="id">ID プロパティの初期値。</param>
        /// <param name="iD_SEKISAN_DATA">ID_SEKISAN_DATA プロパティの初期値。</param>
        /// <param name="iD_MEMBER">ID_MEMBER プロパティの初期値。</param>
        /// <param name="dATETIME_COMMENT">DATETIME_COMMENT プロパティの初期値。</param>
        public static T_COMMENT CreateT_COMMENT(global::System.Int32 id, global::System.Int32 iD_SEKISAN_DATA, global::System.Int32 iD_MEMBER, global::System.DateTime dATETIME_COMMENT)
        {
            T_COMMENT t_COMMENT = new T_COMMENT();
            t_COMMENT.ID = id;
            t_COMMENT.ID_SEKISAN_DATA = iD_SEKISAN_DATA;
            t_COMMENT.ID_MEMBER = iD_MEMBER;
            t_COMMENT.DATETIME_COMMENT = dATETIME_COMMENT;
            return t_COMMENT;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_SEKISAN_DATA
        {
            get
            {
                return _ID_SEKISAN_DATA;
            }
            set
            {
                OnID_SEKISAN_DATAChanging(value);
                ReportPropertyChanging("ID_SEKISAN_DATA");
                _ID_SEKISAN_DATA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_SEKISAN_DATA");
                OnID_SEKISAN_DATAChanged();
            }
        }
        private global::System.Int32 _ID_SEKISAN_DATA;
        partial void OnID_SEKISAN_DATAChanging(global::System.Int32 value);
        partial void OnID_SEKISAN_DATAChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_MEMBER
        {
            get
            {
                return _ID_MEMBER;
            }
            set
            {
                OnID_MEMBERChanging(value);
                ReportPropertyChanging("ID_MEMBER");
                _ID_MEMBER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_MEMBER");
                OnID_MEMBERChanged();
            }
        }
        private global::System.Int32 _ID_MEMBER;
        partial void OnID_MEMBERChanging(global::System.Int32 value);
        partial void OnID_MEMBERChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATETIME_COMMENT
        {
            get
            {
                return _DATETIME_COMMENT;
            }
            set
            {
                OnDATETIME_COMMENTChanging(value);
                ReportPropertyChanging("DATETIME_COMMENT");
                _DATETIME_COMMENT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATETIME_COMMENT");
                OnDATETIME_COMMENTChanged();
            }
        }
        private global::System.DateTime _DATETIME_COMMENT;
        partial void OnDATETIME_COMMENTChanging(global::System.DateTime value);
        partial void OnDATETIME_COMMENTChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENT_MESSAGE
        {
            get
            {
                return _COMMENT_MESSAGE;
            }
            set
            {
                OnCOMMENT_MESSAGEChanging(value);
                ReportPropertyChanging("COMMENT_MESSAGE");
                _COMMENT_MESSAGE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENT_MESSAGE");
                OnCOMMENT_MESSAGEChanged();
            }
        }
        private global::System.String _COMMENT_MESSAGE;
        partial void OnCOMMENT_MESSAGEChanging(global::System.String value);
        partial void OnCOMMENT_MESSAGEChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_COMMENT_T_MEMBER", "T_MEMBER")]
        public T_MEMBER T_MEMBER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MEMBER>("sekisanModel.FK_T_COMMENT_T_MEMBER", "T_MEMBER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MEMBER>("sekisanModel.FK_T_COMMENT_T_MEMBER", "T_MEMBER").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_MEMBER> T_MEMBERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MEMBER>("sekisanModel.FK_T_COMMENT_T_MEMBER", "T_MEMBER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_MEMBER>("sekisanModel.FK_T_COMMENT_T_MEMBER", "T_MEMBER", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_COMMENT_T_SEKISAN_DATA", "T_SEKISAN_DATA")]
        public T_SEKISAN_DATA T_SEKISAN_DATA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_COMMENT_T_SEKISAN_DATA", "T_SEKISAN_DATA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_COMMENT_T_SEKISAN_DATA", "T_SEKISAN_DATA").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_SEKISAN_DATA> T_SEKISAN_DATAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_COMMENT_T_SEKISAN_DATA", "T_SEKISAN_DATA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_COMMENT_T_SEKISAN_DATA", "T_SEKISAN_DATA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sekisanModel", Name="T_MASTER_DIFFICULT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_MASTER_DIFFICULT : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい T_MASTER_DIFFICULT オブジェクトを作成します。
        /// </summary>
        /// <param name="id">ID プロパティの初期値。</param>
        public static T_MASTER_DIFFICULT CreateT_MASTER_DIFFICULT(global::System.Int32 id)
        {
            T_MASTER_DIFFICULT t_MASTER_DIFFICULT = new T_MASTER_DIFFICULT();
            t_MASTER_DIFFICULT.ID = id;
            return t_MASTER_DIFFICULT;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CODE
        {
            get
            {
                return _CODE;
            }
            set
            {
                OnCODEChanging(value);
                ReportPropertyChanging("CODE");
                _CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CODE");
                OnCODEChanged();
            }
        }
        private global::System.String _CODE;
        partial void OnCODEChanging(global::System.String value);
        partial void OnCODEChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_SEKISAN_DATA")]
        public EntityCollection<T_SEKISAN_DATA> T_SEKISAN_DATA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_SEKISAN_DATA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_SEKISAN_DATA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sekisanModel", Name="T_MASTER_RATE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_MASTER_RATE : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい T_MASTER_RATE オブジェクトを作成します。
        /// </summary>
        /// <param name="id">ID プロパティの初期値。</param>
        public static T_MASTER_RATE CreateT_MASTER_RATE(global::System.Int32 id)
        {
            T_MASTER_RATE t_MASTER_RATE = new T_MASTER_RATE();
            t_MASTER_RATE.ID = id;
            return t_MASTER_RATE;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CODE
        {
            get
            {
                return _CODE;
            }
            set
            {
                OnCODEChanging(value);
                ReportPropertyChanging("CODE");
                _CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CODE");
                OnCODEChanged();
            }
        }
        private global::System.String _CODE;
        partial void OnCODEChanging(global::System.String value);
        partial void OnCODEChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RATE
        {
            get
            {
                return _RATE;
            }
            set
            {
                OnRATEChanging(value);
                ReportPropertyChanging("RATE");
                _RATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RATE");
                OnRATEChanged();
            }
        }
        private Nullable<global::System.Decimal> _RATE;
        partial void OnRATEChanging(Nullable<global::System.Decimal> value);
        partial void OnRATEChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_SEKISAN_DATA")]
        public EntityCollection<T_SEKISAN_DATA> T_SEKISAN_DATA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_SEKISAN_DATA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_SEKISAN_DATA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sekisanModel", Name="T_MEMBER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_MEMBER : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい T_MEMBER オブジェクトを作成します。
        /// </summary>
        /// <param name="id">ID プロパティの初期値。</param>
        /// <param name="cODE">CODE プロパティの初期値。</param>
        /// <param name="nAME">NAME プロパティの初期値。</param>
        public static T_MEMBER CreateT_MEMBER(global::System.Int32 id, global::System.String cODE, global::System.String nAME)
        {
            T_MEMBER t_MEMBER = new T_MEMBER();
            t_MEMBER.ID = id;
            t_MEMBER.CODE = cODE;
            t_MEMBER.NAME = nAME;
            return t_MEMBER;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODE
        {
            get
            {
                return _CODE;
            }
            set
            {
                OnCODEChanging(value);
                ReportPropertyChanging("CODE");
                _CODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODE");
                OnCODEChanged();
            }
        }
        private global::System.String _CODE;
        partial void OnCODEChanging(global::System.String value);
        partial void OnCODEChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_COMMENT_T_MEMBER", "T_COMMENT")]
        public EntityCollection<T_COMMENT> T_COMMENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_COMMENT>("sekisanModel.FK_T_COMMENT_T_MEMBER", "T_COMMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_COMMENT>("sekisanModel.FK_T_COMMENT_T_MEMBER", "T_COMMENT", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MEMBER", "T_SEKISAN_DATA")]
        public T_SEKISAN_DATA T_SEKISAN_DATA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_SEKISAN_DATA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_SEKISAN_DATA").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_SEKISAN_DATA> T_SEKISAN_DATAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_SEKISAN_DATA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_SEKISAN_DATA>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_SEKISAN_DATA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sekisanModel", Name="T_SEKISAN_DATA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_SEKISAN_DATA : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい T_SEKISAN_DATA オブジェクトを作成します。
        /// </summary>
        /// <param name="id">ID プロパティの初期値。</param>
        /// <param name="iD_CLIENT">ID_CLIENT プロパティの初期値。</param>
        /// <param name="cODE">CODE プロパティの初期値。</param>
        /// <param name="nAME">NAME プロパティの初期値。</param>
        /// <param name="iD_DIFFICULT">ID_DIFFICULT プロパティの初期値。</param>
        /// <param name="iS_KAKUTEI">IS_KAKUTEI プロパティの初期値。</param>
        public static T_SEKISAN_DATA CreateT_SEKISAN_DATA(global::System.Int32 id, global::System.Int32 iD_CLIENT, global::System.String cODE, global::System.String nAME, global::System.Int32 iD_DIFFICULT, global::System.Byte iS_KAKUTEI)
        {
            T_SEKISAN_DATA t_SEKISAN_DATA = new T_SEKISAN_DATA();
            t_SEKISAN_DATA.ID = id;
            t_SEKISAN_DATA.ID_CLIENT = iD_CLIENT;
            t_SEKISAN_DATA.CODE = cODE;
            t_SEKISAN_DATA.NAME = nAME;
            t_SEKISAN_DATA.ID_DIFFICULT = iD_DIFFICULT;
            t_SEKISAN_DATA.IS_KAKUTEI = iS_KAKUTEI;
            return t_SEKISAN_DATA;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_CLIENT
        {
            get
            {
                return _ID_CLIENT;
            }
            set
            {
                OnID_CLIENTChanging(value);
                ReportPropertyChanging("ID_CLIENT");
                _ID_CLIENT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_CLIENT");
                OnID_CLIENTChanged();
            }
        }
        private global::System.Int32 _ID_CLIENT;
        partial void OnID_CLIENTChanging(global::System.Int32 value);
        partial void OnID_CLIENTChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODE
        {
            get
            {
                return _CODE;
            }
            set
            {
                OnCODEChanging(value);
                ReportPropertyChanging("CODE");
                _CODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODE");
                OnCODEChanged();
            }
        }
        private global::System.String _CODE;
        partial void OnCODEChanging(global::System.String value);
        partial void OnCODEChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CODE_TASK
        {
            get
            {
                return _CODE_TASK;
            }
            set
            {
                OnCODE_TASKChanging(value);
                ReportPropertyChanging("CODE_TASK");
                _CODE_TASK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CODE_TASK");
                OnCODE_TASKChanged();
            }
        }
        private global::System.String _CODE_TASK;
        partial void OnCODE_TASKChanging(global::System.String value);
        partial void OnCODE_TASKChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME_TASK
        {
            get
            {
                return _NAME_TASK;
            }
            set
            {
                OnNAME_TASKChanging(value);
                ReportPropertyChanging("NAME_TASK");
                _NAME_TASK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME_TASK");
                OnNAME_TASKChanged();
            }
        }
        private global::System.String _NAME_TASK;
        partial void OnNAME_TASKChanging(global::System.String value);
        partial void OnNAME_TASKChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HOUR
        {
            get
            {
                return _HOUR;
            }
            set
            {
                OnHOURChanging(value);
                ReportPropertyChanging("HOUR");
                _HOUR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HOUR");
                OnHOURChanged();
            }
        }
        private Nullable<global::System.Decimal> _HOUR;
        partial void OnHOURChanging(Nullable<global::System.Decimal> value);
        partial void OnHOURChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_RATIO
        {
            get
            {
                return _ID_RATIO;
            }
            set
            {
                OnID_RATIOChanging(value);
                ReportPropertyChanging("ID_RATIO");
                _ID_RATIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_RATIO");
                OnID_RATIOChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_RATIO;
        partial void OnID_RATIOChanging(Nullable<global::System.Int32> value);
        partial void OnID_RATIOChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> KINGAKU
        {
            get
            {
                return _KINGAKU;
            }
            set
            {
                OnKINGAKUChanging(value);
                ReportPropertyChanging("KINGAKU");
                _KINGAKU = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KINGAKU");
                OnKINGAKUChanged();
            }
        }
        private Nullable<global::System.Decimal> _KINGAKU;
        partial void OnKINGAKUChanging(Nullable<global::System.Decimal> value);
        partial void OnKINGAKUChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_DIFFICULT
        {
            get
            {
                return _ID_DIFFICULT;
            }
            set
            {
                OnID_DIFFICULTChanging(value);
                ReportPropertyChanging("ID_DIFFICULT");
                _ID_DIFFICULT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_DIFFICULT");
                OnID_DIFFICULTChanged();
            }
        }
        private global::System.Int32 _ID_DIFFICULT;
        partial void OnID_DIFFICULTChanging(global::System.Int32 value);
        partial void OnID_DIFFICULTChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MEMO1
        {
            get
            {
                return _MEMO1;
            }
            set
            {
                OnMEMO1Changing(value);
                ReportPropertyChanging("MEMO1");
                _MEMO1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MEMO1");
                OnMEMO1Changed();
            }
        }
        private global::System.String _MEMO1;
        partial void OnMEMO1Changing(global::System.String value);
        partial void OnMEMO1Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MEMO2
        {
            get
            {
                return _MEMO2;
            }
            set
            {
                OnMEMO2Changing(value);
                ReportPropertyChanging("MEMO2");
                _MEMO2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MEMO2");
                OnMEMO2Changed();
            }
        }
        private global::System.String _MEMO2;
        partial void OnMEMO2Changing(global::System.String value);
        partial void OnMEMO2Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_MEMBER
        {
            get
            {
                return _ID_MEMBER;
            }
            set
            {
                OnID_MEMBERChanging(value);
                ReportPropertyChanging("ID_MEMBER");
                _ID_MEMBER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_MEMBER");
                OnID_MEMBERChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_MEMBER;
        partial void OnID_MEMBERChanging(Nullable<global::System.Int32> value);
        partial void OnID_MEMBERChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IS_KAKUTEI
        {
            get
            {
                return _IS_KAKUTEI;
            }
            set
            {
                OnIS_KAKUTEIChanging(value);
                ReportPropertyChanging("IS_KAKUTEI");
                _IS_KAKUTEI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IS_KAKUTEI");
                OnIS_KAKUTEIChanged();
            }
        }
        private global::System.Byte _IS_KAKUTEI;
        partial void OnIS_KAKUTEIChanging(global::System.Byte value);
        partial void OnIS_KAKUTEIChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_CLIENT", "T_CLIENT")]
        public T_CLIENT T_CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_CLIENT>("sekisanModel.FK_T_SEKISAN_DATA_T_CLIENT", "T_CLIENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_CLIENT>("sekisanModel.FK_T_SEKISAN_DATA_T_CLIENT", "T_CLIENT").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_CLIENT> T_CLIENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_CLIENT>("sekisanModel.FK_T_SEKISAN_DATA_T_CLIENT", "T_CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_CLIENT>("sekisanModel.FK_T_SEKISAN_DATA_T_CLIENT", "T_CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_COMMENT_T_SEKISAN_DATA", "T_COMMENT")]
        public EntityCollection<T_COMMENT> T_COMMENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_COMMENT>("sekisanModel.FK_T_COMMENT_T_SEKISAN_DATA", "T_COMMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_COMMENT>("sekisanModel.FK_T_COMMENT_T_SEKISAN_DATA", "T_COMMENT", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_MASTER_DIFFICULT")]
        public T_MASTER_DIFFICULT T_MASTER_DIFFICULT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MASTER_DIFFICULT>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_MASTER_DIFFICULT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MASTER_DIFFICULT>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_MASTER_DIFFICULT").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_MASTER_DIFFICULT> T_MASTER_DIFFICULTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MASTER_DIFFICULT>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_MASTER_DIFFICULT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_MASTER_DIFFICULT>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_DIFFICULT", "T_MASTER_DIFFICULT", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_MASTER_RATE")]
        public T_MASTER_RATE T_MASTER_RATE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MASTER_RATE>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_MASTER_RATE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MASTER_RATE>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_MASTER_RATE").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_MASTER_RATE> T_MASTER_RATEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MASTER_RATE>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_MASTER_RATE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_MASTER_RATE>("sekisanModel.FK_T_SEKISAN_DATA_T_MASTER_RATE", "T_MASTER_RATE", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sekisanModel", "FK_T_SEKISAN_DATA_T_MEMBER", "T_MEMBER")]
        public T_MEMBER T_MEMBER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MEMBER>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_MEMBER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MEMBER>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_MEMBER").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_MEMBER> T_MEMBERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MEMBER>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_MEMBER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_MEMBER>("sekisanModel.FK_T_SEKISAN_DATA_T_MEMBER", "T_MEMBER", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
